# Universal functions

In [33]:
import numpy as np

In [34]:
angulos_cero_noventa = np.array((0,30,45,60,90))

In [35]:
angulos_cero_noventa

array([ 0, 30, 45, 60, 90])

In [36]:
np.pi

3.141592653589793

In [37]:
angulo_radianes = angulos_cero_noventa * np.pi / 180

In [38]:
angulo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [39]:
np.sin(angulo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [40]:
np.cos(angulo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [41]:
np.tan(angulo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [42]:
arreglo_randomico = np.random.randn(10)

In [43]:
arreglo_randomico

array([-0.03666831, -0.33925497,  0.50467054,  0.53645865,  1.26791684,
        0.24370748, -1.46722356, -0.46159266, -0.52019573,  0.05141544])

In [44]:
arreglo_randomico = arreglo_randomico *10

In [45]:
arreglo_randomico

array([ -0.36668312,  -3.39254973,   5.0467054 ,   5.36458651,
        12.67916843,   2.43707483, -14.6722356 ,  -4.61592664,
        -5.2019573 ,   0.51415441])

In [57]:
arreglo_randomico_diez = np.random.randint(0, 45, 10)

In [59]:
arreglo_randomico_diez

array([13, 22, 19, 16, 44, 39, 18, 43, 15, 28])

In [60]:
#media
arreglo_randomico_diez.mean()

25.7

In [67]:
#mediana
np.median(arreglo_randomico_diez)

TypeError: 'numpy.ndarray' object is not callable

In [52]:
np.median

array([39, 41, 29, 12, 38, 12,  9, 10,  9, 39])

In [66]:
# Desviacion estandar
np.std(arreglo_randomico_diez)

11.419719786404569

In [71]:
#mediana   verificar esto despues
np.median(arreglo_randomico_diez)

TypeError: 'numpy.ndarray' object is not callable

In [72]:
#Varianza
np.var(arreglo_randomico_diez)

130.41000000000003