# Slicing and dicing

In [5]:
import numpy as np

In [9]:
arreglo_once_cuadrado =np.arange(11)**2

In [10]:
arreglo_once_cuadrado

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
arreglo_once_cuadrado[5]

25

In [15]:
arreglo_once_cuadrado[0:3]

array([0, 1, 4], dtype=int32)

In [16]:
arreglo_once_cuadrado[-5:-1]

array([36, 49, 64, 81], dtype=int32)

In [17]:
arreglo_once_cuadrado[3:]

array([  9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [26]:
arreglo_once_cuadrado[-5:9]

array([36, 49, 64], dtype=int32)

In [27]:
arreglo_once_cuadrado[:-6]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [29]:
arreglo_once_cuadrado[0:54:3] # desde una posicion hastaa otra en saltos

array([ 0,  9, 36, 81], dtype=int32)

In [31]:
arreglo_once_cuadrado[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [34]:
for numero in arreglo_once_cuadrado[::-1]:
    print (numero)

100
81
64
49
36
25
16
9
4
1
0
